<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'test',
                'firstname' => 'test',
                'lastname' => 'tester',
                'bio' => 'asdfsadffasdf',
                'profilepicture' => 'icon3',
                'profilecolor' => '#117F65',
                'email' => 'a@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jcQVBzJ5uvTbqS4J1QO4juoLydqXWQpiEpu6ECyWqo4dPNCdCfqWq',
                'remember_token' => NULL,
                'created_at' => '2022-01-24 16:41:56',
                'updated_at' => '2022-03-15 05:31:40',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'asrtro',
                'firstname' => 'alan',
                'lastname' => 'astro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'asrtro@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iLo3dCQEivUVHZHH6PgvkeBoW1SCngrzIsJLBqR1dzstZr7U1BMBO',
                'remember_token' => NULL,
                'created_at' => '2022-01-25 21:59:07',
                'updated_at' => '2022-01-25 21:59:11',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'je',
                'firstname' => 'jeich',
                'lastname' => 'eich',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'je@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.NMLjapyDbFs1QCz22.YFO/ChixPKpqdBAOLVe8/tUTXCAeST4IUe',
                'remember_token' => NULL,
                'created_at' => '2022-01-25 23:48:02',
                'updated_at' => '2022-01-25 23:48:02',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'je11',
                'firstname' => 'j',
                'lastname' => 'e',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#4982DB',
                'email' => 'je11@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0TlMFSGcPn4t0ww3yF5mGuFPfXBFOvUvFOYQx2xPQhfskP5P2epCW',
                'remember_token' => NULL,
                'created_at' => '2022-01-25 23:50:07',
                'updated_at' => '2022-03-17 19:20:01',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'alan220126',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220126@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fV60iKPYAe3ajXabJWW/iuZsEsQX0fg/POmQX8at8dUBZSBsOg2H.',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 15:45:07',
                'updated_at' => '2022-01-26 15:45:12',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'alan220125v2',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220125v2@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$koRR2Qi41HS4JNPDiJIjfeyH6A7prhqM0q2jk.sFJ3Gh0tif.86Wu',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 16:57:02',
                'updated_at' => '2022-01-26 16:57:05',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'alan220125',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'alan220125@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$SoOurcAzGrj8r/bHFzk2xeQioP0PSqTnO/ZrvjCW0D8LbIty0yziC',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 17:37:14',
                'updated_at' => '2022-01-26 17:37:14',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'alan220125v3',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220125v3@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1m7g2sBBIyfxA78gF3CpquHw8s9ZPTzhLnG6Y68EvsPTgpvZSOxpC',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 17:45:52',
                'updated_at' => '2022-01-26 17:48:02',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'alan220125v4',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220125v4@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3pyi..YBW6O34gIbLcVe5OkgF7AG9Klfv7gwalAl3A5wJRzZGNtrq',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 19:09:18',
                'updated_at' => '2022-01-26 19:09:21',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'seexiong',
                'firstname' => 'see',
                'lastname' => 'xiong',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'seexiong@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$obmsfwUsNKizXDCjyWGRseAxwjKn3DyvAXQb98NBjByjHHd.OavrS',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 23:17:48',
                'updated_at' => '2022-01-26 23:17:48',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'xiong',
                'firstname' => 'see',
                'lastname' => 'xiong',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'xiong@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/wXO3P9ImRZ1TS3pGC4zm.brv9kONY46pJ3aHaP20gthY985Kkk/e',
                'remember_token' => NULL,
                'created_at' => '2022-01-26 23:29:44',
                'updated_at' => '2022-01-26 23:29:44',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'ssTest',
                'firstname' => 'Sunita',
                'lastname' => 'Shah',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#FF006A',
                'email' => 'ssTest@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7Q64I4Q3nzTBj.x1z5SKxuh91euYEl1IAuDdKjh8JfVeLEqWdjyXC',
                'remember_token' => NULL,
                'created_at' => '2022-01-27 01:23:35',
                'updated_at' => '2022-01-27 01:24:16',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'rromero',
                'firstname' => 'richie',
                'lastname' => 'romero',
                'bio' => '',
                'profilepicture' => 'icon7',
                'profilecolor' => '#00FF4A',
                'email' => 'rromero@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$tGD3muBOf.fZg3UNHVbq3Oy6qC3bcApGMzktZyWzQyuKDwyPHnr8G',
                'remember_token' => NULL,
                'created_at' => '2022-01-27 14:20:33',
                'updated_at' => '2022-01-27 14:20:47',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'alan220131',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => 'creative director creative director creative director creati',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'alan220131@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0pm1RYQrLlDfs6v/gEzpqua49HSIk2cdAXsITQutu4GzkGvZ2Jm1y',
                'remember_token' => NULL,
                'created_at' => '2022-01-31 16:37:29',
                'updated_at' => '2022-01-31 16:39:38',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'alan220131v2',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => 'creative director creative director creative director creati',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'alan220131v2@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$WWMjW2HpXEn.L7iZ728BceABDtgAiiUv/TQMe1D6xKKOE3GQV5K8y',
                'remember_token' => NULL,
                'created_at' => '2022-01-31 18:21:29',
                'updated_at' => '2022-01-31 18:32:36',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'alan220131v4',
                'firstname' => 'alan',
                'lastname' => 'Castro',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9C9',
                'email' => 'alan220131v4@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$xG7mmHgaWTQ.zslopTH3quGwZrriv0xKK/2bm4TYm0ABRe..r9wTm',
                'remember_token' => NULL,
                'created_at' => '2022-01-31 18:57:23',
                'updated_at' => '2022-01-31 18:57:58',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'ingobingo14',
                'firstname' => 'ingrid',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'ingobingo14@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$qAV79hhFVdgInoeIqOBh1uSPHxCAgnLOaqeQp24e2KujEGZ4vW5Ye',
                'remember_token' => NULL,
                'created_at' => '2022-01-31 23:46:09',
                'updated_at' => '2022-01-31 23:46:09',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'ssTest2',
                'firstname' => 'Sunita',
                'lastname' => 'Shah',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'ssTest2@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6K1R1qR6HbWJ1V4zJ/XZKeJnh7aRy17YXFzytXtMkZ96jdEDPDRtC',
                'remember_token' => NULL,
                'created_at' => '2022-02-01 00:36:19',
                'updated_at' => '2022-02-01 00:36:19',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'ssTest3',
                'firstname' => 'Sunita',
                'lastname' => 'Shah',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#28C789',
                'email' => 'ssTest3@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NHriiJbQNU96cNSWpf3wCOAOMk16hwBcoomVxk3gmWoSO.cg1aMa.',
                'remember_token' => NULL,
                'created_at' => '2022-02-01 00:45:26',
                'updated_at' => '2022-03-09 16:56:11',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'tester4',
                'firstname' => 'test',
                'lastname' => 'test',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'tester4@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DYbXA8cOrM28TUMEp2lfXevDIoNIxUMpYFoB5Fv3sHftPfCyOpFcG',
                'remember_token' => NULL,
                'created_at' => '2022-02-01 16:03:55',
                'updated_at' => '2022-02-01 16:03:55',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'see',
                'firstname' => 'See',
                'lastname' => 'Xiong',
                'bio' => '',
                'profilepicture' => 'icon3',
                'profilecolor' => '#0F8063',
                'email' => 'see@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6UatkMj4xZ/BxCDaZoMc7eHvX5wROIVAj17i/EXb2FatJB5q3KKve',
                'remember_token' => NULL,
                'created_at' => '2022-02-01 16:19:59',
                'updated_at' => '2022-02-01 16:20:40',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'sxiong',
                'firstname' => 'see',
                'lastname' => 'xiong',
                'bio' => 'my bio',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'sxiong@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y.IkTBYw8zuudoQPCHPIYuFuGDbKUaSG06xm9vYrEeLg.jk8XtIRu',
                'remember_token' => NULL,
                'created_at' => '2022-02-01 16:23:28',
                'updated_at' => '2022-02-01 16:51:27',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'micahtest',
                'firstname' => 'Micah',
                'lastname' => 'Holiday',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'micahtest@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mzZDgKg8JG3JQRHPMqpqie5CoPb4XyP9VqcC04d8k4IZCkkjUlNQu',
                'remember_token' => NULL,
                'created_at' => '2022-02-01 18:29:26',
                'updated_at' => '2022-02-01 18:29:26',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'asdf',
                'firstname' => 'a',
                'lastname' => 'a',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#2AC78B',
                'email' => 'asdf@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FotANBoaktTvzfjgQnJ5k.i7Gwz6SGgMem8dIZ6uhhk.TIHT8JV9O',
                'remember_token' => NULL,
                'created_at' => '2022-02-02 18:22:31',
                'updated_at' => '2022-02-02 18:23:37',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ssTest4',
                'firstname' => 'sunita',
                'lastname' => 'shah',
                'bio' => '',
                'profilepicture' => 'icon6',
                'profilecolor' => '#E35D6D',
                'email' => 'ssTest4@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YHexg9E0QUTJuYMqH7tnPezc1xjFCJaoaNtRSoasNkrcepsnyl21e',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 05:16:14',
                'updated_at' => '2022-03-18 17:17:11',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'asdfggg',
                'firstname' => 'sadf',
                'lastname' => 'asdf',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'asdfggg@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6weqbSB3OKPDElSiBglOeO7vSSmjG5xw57iXRhQolg5//c69oCljq',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 11:32:11',
                'updated_at' => '2022-02-03 11:32:11',
            ),
            26 => 
            array (
                'id' => 31,
                'name' => 'alan220203',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#CFD170',
                'email' => 'alan220203@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fOk4jk3ulD1u7VZa1b/Vh.nxWuL.6gkufp.I4LRb3w7PB/DNAEoeG',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 16:47:48',
                'updated_at' => '2022-02-03 16:48:00',
            ),
            27 => 
            array (
                'id' => 32,
                'name' => 'mictest',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'mictest@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$B/lD5.ogSRaejFh3XM5Ap.vl3FEOpo2YQppd0pM1YeFff9XoWK/YG',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 18:08:03',
                'updated_at' => '2022-02-03 18:08:03',
            ),
            28 => 
            array (
                'id' => 33,
                'name' => 'mictest123',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'mictest123@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0e0X1wBbg/yKctHIduTpsOyamUWK0wvuFmrzkf1IoSK7Ov9ycWYNy',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 18:22:45',
                'updated_at' => '2022-02-03 18:22:49',
            ),
            29 => 
            array (
                'id' => 34,
                'name' => 'micah',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'micah@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Aj08.pTiEiw5kDnRuO1d8OZ8kCXAV8gnfsy6RNmJjyPsuRCXkIpA.',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 18:26:26',
                'updated_at' => '2022-02-03 18:26:26',
            ),
            30 => 
            array (
                'id' => 35,
                'name' => 'qwert',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'qwert@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ao2tb7M.rgodpm0z43JWBuidvyndDa1Dz8ZQ7GU4MOfMCB2v3gPqe',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 18:42:32',
                'updated_at' => '2022-02-03 18:42:36',
            ),
            31 => 
            array (
                'id' => 36,
                'name' => 'alan220203v2',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220203v2@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.WyFZz3Wgk4Wrox19PEnnOvJxFFbfgfcM1dftlUPJME.bwfil.SZ.',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 19:09:23',
                'updated_at' => '2022-02-03 19:10:15',
            ),
            32 => 
            array (
                'id' => 37,
                'name' => 'alan220203v3',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220203v3@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$PRvDTF7xdwD0jvuIylsdy.AU.A65VjbmGHZdCnHx5hxW2nnkRYzqO',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 19:11:59',
                'updated_at' => '2022-02-03 19:22:10',
            ),
            33 => 
            array (
                'id' => 38,
                'name' => 'asdfg',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'asdfg@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$kwqIwgxllWN28yHRguOpMuTU1jK36yUFrPb3ZBKVuSYN9a2S5sERa',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 19:33:10',
                'updated_at' => '2022-02-03 19:33:15',
            ),
            34 => 
            array (
                'id' => 39,
                'name' => 'see2',
                'firstname' => 'See',
                'lastname' => 'Xiong',
                'bio' => 'Hello world.',
                'profilepicture' => 'icon6',
                'profilecolor' => '#E45F6D',
                'email' => 'see2@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y4QE45gJqBxNGlAOCSRO1.ybI88mt7zpduLL1qxGhkeWqtG46w/GW',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 19:58:27',
                'updated_at' => '2022-02-03 23:59:25',
            ),
            35 => 
            array (
                'id' => 40,
                'name' => 'holi',
                'firstname' => 'micah',
                'lastname' => 'holi',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'holi@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3IKVd9kA7ysYWq/YWVQmLORxDlQNtxg7ZdekmelFGEeGGTII9SzvS',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 20:03:09',
                'updated_at' => '2022-02-03 20:03:09',
            ),
            36 => 
            array (
                'id' => 41,
                'name' => 'ikintest',
                'firstname' => 'test',
                'lastname' => 'ikin',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'ikintest@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yD4j5FSe4T11bUSA3tK/deUiuK4kX1yq1U55OmUWl/41ArI3T92He',
                'remember_token' => NULL,
                'created_at' => '2022-02-03 23:26:22',
                'updated_at' => '2022-02-03 23:26:27',
            ),
            37 => 
            array (
                'id' => 42,
                'name' => 'micheck',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => 'icon4',
                'profilecolor' => '#BD93DA',
                'email' => 'micheck@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QJo.F4ZMRdNaDNelbYp4QuRkkB0iDrSzGnCsZxeY.igSKKfms9a9u',
                'remember_token' => NULL,
                'created_at' => '2022-02-07 18:10:23',
                'updated_at' => '2022-02-08 19:24:46',
            ),
            38 => 
            array (
                'id' => 43,
                'name' => 'alan0207',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#4982DB',
                'email' => 'alan0207@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zbD0uS1VpgjsqZmMegFRCOMNl1FYhQbAwAU9.s5mzpy9QgJfnCB7K',
                'remember_token' => NULL,
                'created_at' => '2022-02-07 19:48:04',
                'updated_at' => '2022-02-07 19:48:22',
            ),
            39 => 
            array (
                'id' => 44,
                'name' => 'alan0208',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => 'Creative Director Creative Director Creative Director Creati',
                'profilepicture' => 'icon4',
                'profilecolor' => '#4982DB',
                'email' => 'alan0208@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$IzCljrEp7SjtfacGKQ4ZGuycQ3uiVc6ktoRmhpL7kYZ245qskW6Xq',
                'remember_token' => NULL,
                'created_at' => '2022-02-07 19:56:07',
                'updated_at' => '2022-02-07 19:57:45',
            ),
            40 => 
            array (
                'id' => 45,
                'name' => 'seetest',
                'firstname' => 'See',
                'lastname' => 'Test',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#2AC78B',
                'email' => 'seetest@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VbvAM6Ylye6eYcf88T48N.C2gpyS0sL4pB/hHnyVzNRcyk.OyQXJO',
                'remember_token' => NULL,
                'created_at' => '2022-02-08 17:34:12',
                'updated_at' => '2022-02-08 17:35:19',
            ),
            41 => 
            array (
                'id' => 46,
                'name' => 'nametest',
                'firstname' => 'test',
                'lastname' => 'tester',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'nametest@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$piSeuKPIzlR3PKQ5aaNjE.6cx7IUQypfGzEDyplnNHh48Uaxs3ZlC',
                'remember_token' => NULL,
                'created_at' => '2022-02-09 00:20:28',
                'updated_at' => '2022-02-09 00:20:28',
            ),
            42 => 
            array (
                'id' => 47,
                'name' => 'alan220214',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon6',
                'profilecolor' => '#E45F6D',
                'email' => 'alan220214@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pwHyrqurRvjnT9MN.924eOB0kvuAXOZg1ZLoigjT35hGCQw6x2iP.',
                'remember_token' => NULL,
                'created_at' => '2022-02-14 23:55:29',
                'updated_at' => '2022-02-14 23:55:36',
            ),
            43 => 
            array (
                'id' => 48,
                'name' => 'hhhhhh',
                'firstname' => 'r',
                'lastname' => 'ggff',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#4982DB',
                'email' => 'hhhhhh@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0eeu3CKReO2J/4QRE/RPf.96BisDoixGMRbBQlHVf3s6GfMApa1oW',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:08:00',
                'updated_at' => '2022-03-12 05:08:07',
            ),
            44 => 
            array (
                'id' => 49,
                'name' => 'aaaaaa',
                'firstname' => 'bla',
                'lastname' => 'vvv',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4DD9C9',
                'email' => 'aaaaaa@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$OhYisyqLjIu6a.qT1LKNwuc0EJ45xAGJMCGVfbI35JCMy20C0jvza',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:14:51',
                'updated_at' => '2022-03-12 05:14:54',
            ),
            45 => 
            array (
                'id' => 50,
                'name' => 'qwerty',
                'firstname' => 'asdf',
                'lastname' => 'aswwqda',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'qwerty@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0IKz0RdQIQCeTDJev0n8P.nivPdlUQlLL2luOkCMUOjc/NVmhQkE.',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:18:48',
                'updated_at' => '2022-03-12 05:18:51',
            ),
            46 => 
            array (
                'id' => 51,
                'name' => 'gggggg',
                'firstname' => 'ffff',
                'lastname' => 'ffff',
                'bio' => '',
                'profilepicture' => 'icon3',
                'profilecolor' => '#117F65',
                'email' => 'gggggg@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$w33EcO8a1FbHFuxCgu9QDOciZfYTD8j7Tk0OxpNKjAVWHxA3g5/Qa',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:22:52',
                'updated_at' => '2022-03-12 05:22:56',
            ),
            47 => 
            array (
                'id' => 52,
                'name' => 'asasas',
                'firstname' => 'fa',
                'lastname' => 'fa',
                'bio' => '',
                'profilepicture' => 'icon6',
                'profilecolor' => '#E45F6D',
                'email' => 'asasas@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$E6DuxTgPwXA3N5BqAxtXWeRfoyP1eMzaxT.3I/NkqYqS.bLW.k9a6',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:25:52',
                'updated_at' => '2022-03-12 05:25:57',
            ),
            48 => 
            array (
                'id' => 53,
                'name' => 'ioioio',
                'firstname' => 'ioioi',
                'lastname' => 'ioioi',
                'bio' => '',
                'profilepicture' => 'icon4',
                'profilecolor' => '#BD93DA',
                'email' => 'ioioio@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$H/X71GKFcUB7vRF4gh898OaF3QvL7miJ/r/Wrga/hnEiitA1v2E6m',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:28:50',
                'updated_at' => '2022-03-12 05:28:53',
            ),
            49 => 
            array (
                'id' => 54,
                'name' => 'wert',
                'firstname' => 'wert',
                'lastname' => 'wert',
                'bio' => '',
                'profilepicture' => 'icon7',
                'profilecolor' => '#D89589',
                'email' => 'wert@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hLQ9Cd87Bu8eWuonLLt8pOADrhl0Eje5T3cSW8nDqzexgbISZsX8K',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:34:03',
                'updated_at' => '2022-03-12 05:34:07',
            ),
            50 => 
            array (
                'id' => 55,
                'name' => 'gggg',
                'firstname' => 'gg',
                'lastname' => 'gg',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'gggg@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$XmJYWWL47nsr2v9sXtYnYuTbdLb25Q5IZi7ryUdja/Kt054Pe8Wdq',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:41:35',
                'updated_at' => '2022-03-12 05:41:38',
            ),
            51 => 
            array (
                'id' => 56,
                'name' => 'tttt',
                'firstname' => 'tttt',
                'lastname' => 'tttt',
                'bio' => '',
                'profilepicture' => 'icon4',
                'profilecolor' => '#BD93DA',
                'email' => 'tttt@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$UcYIoA2AW7th9yn1wSLajOCbbCwkQ2w//ojgD.6LxxjDJPvuQdaDG',
                'remember_token' => NULL,
                'created_at' => '2022-03-12 05:48:34',
                'updated_at' => '2022-03-12 05:48:37',
            ),
            52 => 
            array (
                'id' => 57,
                'name' => 'ttttttt',
                'firstname' => 'testttt',
                'lastname' => 'tt',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'ttttttt@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$q1ut.7rF.X7tUIZzCno.n.bepT9GKiImuAAneKgZz1hLtXpP3eKTu',
                'remember_token' => NULL,
                'created_at' => '2022-03-13 06:38:22',
                'updated_at' => '2022-03-13 06:38:22',
            ),
            53 => 
            array (
                'id' => 58,
                'name' => 'ytytyty',
                'firstname' => 'ty',
                'lastname' => 'ty',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'ytytyty@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$BjHKk65FWLS4NzDl5gSRqeZUeLC2QQ6IWAhg8OUcMfRFTheDoQe16',
                'remember_token' => NULL,
                'created_at' => '2022-03-13 06:57:01',
                'updated_at' => '2022-03-13 06:57:01',
            ),
            54 => 
            array (
                'id' => 59,
                'name' => 'asdad',
                'firstname' => 'a',
                'lastname' => 'a',
                'bio' => '',
                'profilepicture' => 'icon7',
                'profilecolor' => '#D89589',
                'email' => 'asdad@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rPsZO9CqN/6vxpiB1aDOwuHTjjbr7jQQYIEr8ovza3pnAQBmP66FS',
                'remember_token' => NULL,
                'created_at' => '2022-03-14 07:47:21',
                'updated_at' => '2022-03-14 07:47:29',
            ),
            55 => 
            array (
                'id' => 60,
                'name' => 'jamison',
                'firstname' => 'jamison',
                'lastname' => 'e',
                'bio' => '',
                'profilepicture' => NULL,
                'profilecolor' => NULL,
                'email' => 'jamison@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$v78jNm3DIX8MCUL5wUzjkOmyAL5nXpTqr5cQPhfzPrwqp5oJKvgMm',
                'remember_token' => NULL,
                'created_at' => '2022-03-14 18:55:33',
                'updated_at' => '2022-03-14 18:55:33',
            ),
            56 => 
            array (
                'id' => 61,
                'name' => 'alan14mar',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4982DB',
                'email' => 'alan14mar@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3rmDQmRIcIXvabjfxp01SuF58uUsxr9pSo4s1tXpvYhZfJWEqkHpC',
                'remember_token' => NULL,
                'created_at' => '2022-03-14 22:16:58',
                'updated_at' => '2022-03-14 22:20:02',
            ),
            57 => 
            array (
                'id' => 62,
                'name' => 'seetest1',
                'firstname' => 'see',
                'lastname' => 'xiong',
                'bio' => '',
                'profilepicture' => 'icon3',
                'profilecolor' => '#D6948A',
                'email' => 'seetest1@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$XHBxWr98GAaMnZ60mJyaS.rhBwylUzmxLBkbu33add4JYJXtnRjLC',
                'remember_token' => NULL,
                'created_at' => '2022-03-14 22:59:30',
                'updated_at' => '2022-03-14 22:59:38',
            ),
            58 => 
            array (
                'id' => 63,
                'name' => 'test12e4',
                'firstname' => 'see',
                'lastname' => 'z',
                'bio' => '',
                'profilepicture' => 'icon7',
                'profilecolor' => '#D89589',
                'email' => 'test12e4@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZrQghHDkSxR4M6Qa58HtHOcV/bXyn6aY5ymxUx5oAFjsaPOtqSsAi',
                'remember_token' => NULL,
                'created_at' => '2022-03-16 18:18:17',
                'updated_at' => '2022-03-16 18:18:29',
            ),
            59 => 
            array (
                'id' => 64,
                'name' => 'jjee',
                'firstname' => 'jay',
                'lastname' => 'e',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'jjee@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$qyICR63aIewk6TENQbCvTeoJAjBYap/9moR.56lx9EPQveSPcDSJO',
                'remember_token' => NULL,
                'created_at' => '2022-03-17 18:44:06',
                'updated_at' => '2022-03-17 18:44:10',
            ),
            60 => 
            array (
                'id' => 65,
                'name' => 'ssTest5',
                'firstname' => 'Sunita',
                'lastname' => 'Shah',
                'bio' => '',
                'profilepicture' => 'icon7',
                'profilecolor' => '#D89589',
                'email' => 'ssTest5@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hNh8TZVzWpWTSjExQhw3OONOIOZ/NPR8i00NH.7MTBLwAgT2Bup7u',
                'remember_token' => NULL,
                'created_at' => '2022-03-18 17:37:54',
                'updated_at' => '2022-03-18 17:38:00',
            ),
            61 => 
            array (
                'id' => 66,
                'name' => 'nai',
                'firstname' => 'nadia',
                'lastname' => 'villalba',
                'bio' => '☺️???',
                'profilepicture' => 'icon8',
                'profilecolor' => '#4DD9C9',
                'email' => 'nai@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$L/G1In2hmTzOE8X25C/A4OtEj5C.HWtL/d0a6.qB1h.OzlXWkBRYu',
                'remember_token' => NULL,
                'created_at' => '2022-03-22 21:02:21',
                'updated_at' => '2022-04-05 22:39:30',
            ),
            62 => 
            array (
                'id' => 67,
                'name' => 'alan23mar',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#E35D6D',
                'email' => 'alan23mar@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7hBXrzdOK2YDCnNOdzAV1.XYNCW2.vipY4LOeX6jgS8gFxKFWDhGu',
                'remember_token' => NULL,
                'created_at' => '2022-03-23 16:30:13',
                'updated_at' => '2022-03-23 16:30:29',
            ),
            63 => 
            array (
                'id' => 68,
                'name' => 'rrrr',
                'firstname' => 'frr',
                'lastname' => 'gg',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'rrrr@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$YWdAHPNdCHmuO/GlKqDXS.CUT8vD64NejmanvzFvLl.QMvFSbiq4S',
                'remember_token' => NULL,
                'created_at' => '2022-03-28 14:48:38',
                'updated_at' => '2022-03-28 14:48:41',
            ),
            64 => 
            array (
                'id' => 69,
                'name' => 'hhhh',
                'firstname' => 'hh',
                'lastname' => 'hh',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'hhhh@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cmrc0ck0wJ/ezHGiu/lKJOHK3X40C/by7RO8zbh8jyatnuFSWb7iK',
                'remember_token' => NULL,
                'created_at' => '2022-03-28 14:50:17',
                'updated_at' => '2022-03-28 14:50:20',
            ),
            65 => 
            array (
                'id' => 70,
                'name' => 'ttttt',
                'firstname' => 'hege',
                'lastname' => 'hdbd',
                'bio' => '',
                'profilepicture' => 'icon7',
                'profilecolor' => '#D89589',
                'email' => 'ttttt@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/./c4uD245uVSGcq2U97hegL5uVILTe8Zf/qZsIBXZJiH4Bj0T71q',
                'remember_token' => NULL,
                'created_at' => '2022-03-28 14:51:20',
                'updated_at' => '2022-03-28 14:51:23',
            ),
            66 => 
            array (
                'id' => 71,
                'name' => 'micah67890',
                'firstname' => 'micah',
                'lastname' => 'holiday',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4982DB',
                'email' => 'micah67890@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hKYdeaXU3galZB7DwSo4W.mLakVhUgq.B7HO/6WVAA54a7.5wXkKO',
                'remember_token' => NULL,
                'created_at' => '2022-03-29 18:13:53',
                'updated_at' => '2022-03-29 18:14:09',
            ),
            67 => 
            array (
                'id' => 72,
                'name' => 'imageMaker',
                'firstname' => 'images',
                'lastname' => 'creator',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#CFD170',
                'email' => 'imageMaker@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FIBPoNNyb7sk19tSqAj16enmXNjhFhtY0xl6z2zHRctCkfxw1Qoju',
                'remember_token' => NULL,
                'created_at' => '2022-04-04 18:00:40',
                'updated_at' => '2022-04-04 18:00:59',
            ),
            68 => 
            array (
                'id' => 73,
                'name' => 'richieromero',
                'firstname' => 'richie',
                'lastname' => 'r',
                'bio' => '',
                'profilepicture' => 'icon8',
                'profilecolor' => '#BD91D9',
                'email' => 'richieromero@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$tr0OZzYEYoHqnHI7b/EM.uhZVnZAWl0qijo2VFu8ahxSI4sJbM.9W',
                'remember_token' => NULL,
                'created_at' => '2022-04-04 18:36:25',
                'updated_at' => '2022-04-04 18:36:35',
            ),
            69 => 
            array (
                'id' => 74,
                'name' => 'testnai01',
                'firstname' => 'asdfg',
                'lastname' => 'zxcv67890',
                'bio' => '',
                'profilepicture' => 'icon5',
                'profilecolor' => '#E35D6D',
                'email' => 'testnai01@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$9NwhQrSZdP2YmCowafZt7eD01c6wNIhRyC5wSWSXteIM9KtopLX..',
                'remember_token' => NULL,
                'created_at' => '2022-04-05 22:45:06',
                'updated_at' => '2022-04-05 22:45:15',
            ),
            70 => 
            array (
                'id' => 75,
                'name' => 'alan220406med',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#4A84DD',
                'email' => 'alan220406med@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0.DlVa6Zo1E2GOY.z2vtoOGLmItkjvX3VQ9RtE4tqt6P4xACQ4kke',
                'remember_token' => NULL,
                'created_at' => '2022-04-06 22:09:52',
                'updated_at' => '2022-04-06 22:09:59',
            ),
            71 => 
            array (
                'id' => 76,
                'name' => 'alan220406high',
                'firstname' => 'alan',
                'lastname' => 'castro',
                'bio' => '',
                'profilepicture' => 'icon1',
                'profilecolor' => '#4DD9CA',
                'email' => 'alan220406high@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VDY4yDEYVbkmYNUeGb8O4uyDKzEBIljhcE5ef.oAd7UdGzzssJuR.',
                'remember_token' => NULL,
                'created_at' => '2022-04-06 22:22:20',
                'updated_at' => '2022-04-06 22:22:25',
            ),
            72 => 
            array (
                'id' => 77,
                'name' => 'rromero72',
                'firstname' => 'richie',
                'lastname' => 'romero',
                'bio' => '',
                'profilepicture' => 'icon2',
                'profilecolor' => '#E35D6D',
                'email' => 'rromero72@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$q8lPcNF4BYyv.VKfU5afIeAwBbF6HTX0TDqfjrnaDk4KEYc.dg0ja',
                'remember_token' => NULL,
                'created_at' => '2022-04-11 16:45:48',
                'updated_at' => '2022-04-11 16:45:56',
            ),
            73 => 
            array (
                'id' => 78,
                'name' => 'ikinrocks',
                'firstname' => 'ikin rocks',
                'lastname' => '1',
                'bio' => 'i love ikin',
                'profilepicture' => 'icon5',
                'profilecolor' => '#BD91D9',
                'email' => 'ikinrocks@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zwDOmXi2dxWzdNdSE9rmMeacQiH4oFt/aJ5W1fi0XWgoKpXJiQ6WG',
                'remember_token' => NULL,
                'created_at' => '2022-04-12 19:40:39',
                'updated_at' => '2022-04-12 19:45:53',
            ),
            74 => 
            array (
                'id' => 79,
                'name' => 'RedC',
                'firstname' => 'red',
                'lastname' => 'coffee',
                'bio' => '',
                'profilepicture' => 'icon6',
                'profilecolor' => '#CFD170',
                'email' => 'RedC@ikin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$smmgO7SOjqCN.iM30jvpkeim1qTNf6VMnHCclQEIs0Kf0TQ8jF4XO',
                'remember_token' => NULL,
                'created_at' => '2022-04-12 20:06:04',
                'updated_at' => '2022-04-12 20:06:22',
            ),
        ));
        
        
    }
}